import { Internship } from '../types/internship';

export async function fetchInternships(): Promise<Internship[]> {
  try {
    const res = await fetch('https://internshala.com/hiring/search', {
      next: { revalidate: 3600 },
    });
    console.log('API response status:', res);
    if (!res.ok) throw new Error('API failed');
    const data = await res.json();
    const meta = data.internships_meta || {};
    return Object.values(meta) as Internship[];
  } catch {
    return getMockInternships();
  }
}

export function getMockInternships(): Internship[] {
  return [
    {
      id: 1,
      title: 'Frontend Developer Intern',
      company_name: 'Google',
      company_logo: '',
      company_url: '/company/google',
      profile_name: 'Web Development',
      location_names: ['Bangalore'],
      locations: [{ string: 'Bangalore', locationName: 'Bangalore', country: 'India', region: 'Karnataka' }],
      duration: '3 Months',
      stipend: { salary: '₹ 25,000 /month', salaryValue1: 25000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: 'Starts Immediately',
      posted_on: "15 May' 25",
      application_deadline: "30 May' 25",
      expiring_in: 'Apply by 30 May',
      work_from_home: false,
      part_time: false,
      is_ppo: true,
      is_premium: true,
      is_international_job: false,
      url: 'frontend-developer-internship-google',
      labels_app_in_card: ['Internship', 'PPO'],
    },
    {
      id: 2,
      title: 'Data Science Intern',
      company_name: 'Microsoft',
      company_logo: '',
      company_url: '/company/microsoft',
      profile_name: 'Data Science',
      location_names: ['Work From Home'],
      locations: [],
      duration: '6 Months',
      stipend: { salary: '₹ 40,000 /month', salaryValue1: 40000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: 'Starts Immediately',
      posted_on: "14 May' 25",
      application_deadline: "28 May' 25",
      expiring_in: 'Apply by 28 May',
      work_from_home: true,
      part_time: false,
      is_ppo: false,
      is_premium: true,
      is_international_job: false,
      url: 'data-science-internship-microsoft',
      labels_app_in_card: ['Internship', 'Work From Home'],
    },
    {
      id: 3,
      title: 'UI/UX Design Intern',
      company_name: 'Swiggy',
      company_logo: '',
      company_url: '/company/swiggy',
      profile_name: 'UI/UX Design',
      location_names: ['Mumbai'],
      locations: [{ string: 'Mumbai', locationName: 'Mumbai', country: 'India', region: 'Maharashtra' }],
      duration: '2 Months',
      stipend: { salary: '₹ 15,000 /month', salaryValue1: 15000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: "1 Jun' 25",
      posted_on: "13 May' 25",
      application_deadline: "27 May' 25",
      expiring_in: 'Apply by 27 May',
      work_from_home: false,
      part_time: true,
      is_ppo: false,
      is_premium: false,
      is_international_job: false,
      url: 'ui-ux-design-internship-swiggy',
      labels_app_in_card: ['Internship', 'Part-time'],
    },
    {
      id: 4,
      title: 'Machine Learning Intern',
      company_name: 'Amazon',
      company_logo: '',
      company_url: '/company/amazon',
      profile_name: 'Machine Learning',
      location_names: ['Hyderabad'],
      locations: [{ string: 'Hyderabad', locationName: 'Hyderabad', country: 'India', region: 'Telangana' }],
      duration: '4 Months',
      stipend: { salary: '₹ 60,000 /month', salaryValue1: 60000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: 'Starts Immediately',
      posted_on: "12 May' 25",
      application_deadline: "25 May' 25",
      expiring_in: 'Apply by 25 May',
      work_from_home: false,
      part_time: false,
      is_ppo: true,
      is_premium: true,
      is_international_job: false,
      url: 'machine-learning-internship-amazon',
      labels_app_in_card: ['Internship', 'PPO'],
    },
    {
      id: 5,
      title: 'Marketing & Growth Intern',
      company_name: 'Zomato',
      company_logo: '',
      company_url: '/company/zomato',
      profile_name: 'Digital Marketing',
      location_names: ['Delhi'],
      locations: [{ string: 'Delhi', locationName: 'Delhi', country: 'India', region: null }],
      duration: '3 Months',
      stipend: { salary: '₹ 8,000 /month', salaryValue1: 8000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: "15 Jun' 25",
      posted_on: "11 May' 25",
      application_deadline: "24 May' 25",
      expiring_in: 'Apply by 24 May',
      work_from_home: false,
      part_time: false,
      is_ppo: false,
      is_premium: false,
      is_international_job: false,
      url: 'marketing-internship-zomato',
      labels_app_in_card: ['Internship'],
    },
    {
      id: 6,
      title: 'Backend Developer Intern',
      company_name: 'PhonePe',
      company_logo: '',
      company_url: '/company/phonepe',
      profile_name: 'Web Development',
      location_names: ['Work From Home'],
      locations: [],
      duration: '6 Months',
      stipend: { salary: '₹ 35,000 /month', salaryValue1: 35000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: 'Starts Immediately',
      posted_on: "10 May' 25",
      application_deadline: "23 May' 25",
      expiring_in: 'Apply by 23 May',
      work_from_home: true,
      part_time: false,
      is_ppo: true,
      is_premium: false,
      is_international_job: false,
      url: 'backend-internship-phonepe',
      labels_app_in_card: ['Internship', 'Work From Home', 'PPO'],
    },
    {
      id: 7,
      title: 'Content Writing Intern',
      company_name: 'Times of India',
      company_logo: '',
      company_url: '/company/toi',
      profile_name: 'Content Writing',
      location_names: ['Work From Home'],
      locations: [],
      duration: '2 Months',
      stipend: { salary: '₹ 5,000 /month', salaryValue1: 5000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: 'Starts Immediately',
      posted_on: "9 May' 25",
      application_deadline: "22 May' 25",
      expiring_in: 'Apply by 22 May',
      work_from_home: true,
      part_time: true,
      is_ppo: false,
      is_premium: false,
      is_international_job: false,
      url: 'content-writing-internship-toi',
      labels_app_in_card: ['Internship', 'Work From Home', 'Part-time'],
    },
    {
      id: 8,
      title: 'Product Management Intern',
      company_name: 'Flipkart',
      company_logo: '',
      company_url: '/company/flipkart',
      profile_name: 'Product Management',
      location_names: ['Bangalore'],
      locations: [{ string: 'Bangalore', locationName: 'Bangalore', country: 'India', region: 'Karnataka' }],
      duration: '3 Months',
      stipend: { salary: '₹ 50,000 /month', salaryValue1: 50000, salaryValue2: null, salaryType: 'fixed', currency: 'INR', scale: 'permonth' },
      start_date: "1 Jul' 25",
      posted_on: "8 May' 25",
      application_deadline: "21 May' 25",
      expiring_in: 'Apply by 21 May',
      work_from_home: false,
      part_time: false,
      is_ppo: true,
      is_premium: true,
      is_international_job: false,
      url: 'product-management-internship-flipkart',
      labels_app_in_card: ['Internship', 'PPO'],
    },
  ];
}